version: "3.8"

services:
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    hostname: neo4j
    ports:
      - "7474:7474" # HTTP Neo4j Browser
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/12345678 # Default username and password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8888:8888"
    depends_on:
      - identity-service
      - profile-service
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      SPRING_CLOUD_GATEWAY_ROUTES: |
        - id: identity_service
          uri: http://identity-service:8080
          predicates:
            - Path=/api/v1/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://profile-service:8081
          predicates:
            - Path=/api/v1/profile/users/**
          filters:
            - StripPrefix=2

  identity-service:
    build:
      context: ./identity-service
    container_name: identity-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/bookteria_identity
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      JWT_SIGNER_KEY: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
      JWT_VALID_DURATION: 3600
      JWT_REFRESHABLE_DURATION: 36000
      APP_SERVICES_PROFILE: http://profile-service:8081/profile

  profile-service:
    build:
      context: ./profile-service
    container_name: profile-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/bookteria_profile
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_APPLICATION_NAME: profile-service
      SPRING_DATA_NEO4J_URI: bolt://neo4j:7687
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: 12345678

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: bookteria
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"  # Cổng MySQL 3308 cho ứng dụng

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  mysql_data:
